apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: demoweb 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoweb 
    spec:
      containers:
      - name: demoweb
        image: gcr.io/asia-awoo-com-tw/demoweb:v0.0.1
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80

